### ISSUE TITLE
Word of the day bot 

### ISSUE THREAD

**Issue by Blackwidowraiderette** [halfmatthalfcat/wotd#1]
Hi, word of the day bot gives me an error when adding to discord 
![Screenshot_20230408_100152_Chrome](https://user-images.githubusercontent.com/130235579/230728621-1a8b1015-6320-4f17-8d2f-3efaa03ad46c.jpg)

**Comment by halfmatthalfcat** [comment]
Hi @Blackwidowraiderette - Discord bots that reach 100 servers need to be manually verified by Discord to be added to more. WotD Bot hit 100 servers two weeks and I submitted all the proper docs to them. We're just waiting for them to further approve it. I'll post back here when they finally do. Thanks for checking it out!

**Comment by Blackwidowraiderette** [comment]
Hey thanks! I was actually able to add it to one of my other servers a few weeks ago so I guess I was confused. I'll check back in a week or so and try to add it again to my other one :)

**Comment by halfmatthalfcat** [comment]
@Blackwidowraiderette this should finally be done! Feel free to add to more guilds.
